### ISSUE TITLE
日志打印正常，但是没有发送请求

### ISSUE THREAD

**Issue by qi-guozheng** [WeihuaGu/receiptnotice#23]
你好，安装到小米6上，支付宝收款后，日志也有显示，但未发生post请求，日历里也没有显示关于发送请求的信息。。。

**Comment by qi-guozheng** [comment]
05-13 22:11:58.285 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:11:58.286 25942 25942 D NLService: 2019-05-13 22:11
05-13 22:11:58.287 25942 25942 D NLService:
05-13 22:11:58.287 25942 25942 D NLService:
05-13 22:11:58.287 25942 25942 D NLService: **********************
05-13 22:12:18.316 25942 25942 D NLService: 接受到通知消息
05-13 22:12:18.316 25942 25942 D NLService: -----------------
05-13 22:12:18.316 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:12:18.316 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:12:18.317 25942 25942 D NLService: 2019-05-13 22:12
05-13 22:12:18.317 25942 25942 D NLService:
05-13 22:12:18.317 25942 25942 D NLService:
05-13 22:12:18.317 25942 25942 D NLService: **********************
05-13 22:12:28.330 25942 25942 D NLService: 接受到通知消息
05-13 22:12:28.330 25942 25942 D NLService: -----------------
05-13 22:12:28.330 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:12:28.330 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:12:28.331 25942 25942 D NLService: 2019-05-13 22:12
05-13 22:12:28.331 25942 25942 D NLService:
05-13 22:12:28.331 25942 25942 D NLService:
05-13 22:12:28.331 25942 25942 D NLService: **********************
05-13 22:12:38.338 25942 25942 D NLService: 接受到通知消息
05-13 22:12:38.338 25942 25942 D NLService: -----------------
05-13 22:12:38.338 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:12:38.338 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:12:38.339 25942 25942 D NLService: 2019-05-13 22:12
05-13 22:12:38.339 25942 25942 D NLService:
05-13 22:12:38.339 25942 25942 D NLService:
05-13 22:12:38.339 25942 25942 D NLService: **********************
05-13 22:12:40.407 25942 25942 D NLService: 接受到通知消息
05-13 22:12:40.407 25942 25942 D NLService: -----------------
05-13 22:12:40.409 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:12:40.409 25942 25942 D NLService: 包名是com.eg.android.AlipayGphone
05-13 22:12:40.409 25942 25942 D NLService: 2019-05-13 22:12
05-13 22:12:40.409 25942 25942 D NLService: 支付宝消息
05-13 22:12:40.409 25942 25942 D NLService: **已成功向你转了1笔钱
05-13 22:12:40.409 25942 25942 D NLService: **********************
05-13 22:12:48.351 25942 25942 D NLService: 接受到通知消息
05-13 22:12:48.351 25942 25942 D NLService: -----------------
05-13 22:12:48.351 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:12:48.351 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:12:48.352 25942 25942 D NLService: 2019-05-13 22:12
05-13 22:12:48.352 25942 25942 D NLService:
05-13 22:12:48.352 25942 25942 D NLService:
05-13 22:12:48.352 25942 25942 D NLService: **********************
05-13 22:12:58.357 25942 25942 D NLService: 接受到通知消息
05-13 22:12:58.357 25942 25942 D NLService: -----------------
05-13 22:12:58.357 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:12:58.357 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:12:58.358 25942 25942 D NLService: 2019-05-13 22:12
05-13 22:12:58.358 25942 25942 D NLService:
05-13 22:12:58.358 25942 25942 D NLService:
05-13 22:12:58.358 25942 25942 D NLService: **********************
05-13 22:13:08.370 25942 25942 D NLService: 接受到通知消息
05-13 22:13:08.371 25942 25942 D NLService: -----------------
05-13 22:13:08.371 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:13:08.371 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:13:08.372 25942 25942 D NLService: 2019-05-13 22:13
05-13 22:13:08.372 25942 25942 D NLService:
05-13 22:13:08.372 25942 25942 D NLService:
05-13 22:13:08.372 25942 25942 D NLService: **********************
05-13 22:13:18.384 25942 25942 D NLService: 接受到通知消息
05-13 22:13:18.384 25942 25942 D NLService: -----------------
05-13 22:13:18.384 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:13:18.384 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:13:18.385 25942 25942 D NLService: 2019-05-13 22:13
05-13 22:13:18.385 25942 25942 D NLService:
05-13 22:13:18.385 25942 25942 D NLService:
05-13 22:13:18.385 25942 25942 D NLService: **********************
05-13 22:13:33.398 25942 25942 D NLService: 接受到通知消息
05-13 22:13:33.399 25942 25942 D NLService: -----------------
05-13 22:13:33.399 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:13:33.399 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:13:33.400 25942 25942 D NLService: 2019-05-13 22:13
05-13 22:13:33.400 25942 25942 D NLService:
05-13 22:13:33.400 25942 25942 D NLService:
05-13 22:13:33.400 25942 25942 D NLService: **********************
05-13 22:13:43.416 25942 25942 D NLService: 接受到通知消息
05-13 22:13:43.416 25942 25942 D NLService: -----------------
05-13 22:13:43.416 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:13:43.416 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:13:43.417 25942 25942 D NLService: 2019-05-13 22:13
05-13 22:13:43.417 25942 25942 D NLService:
05-13 22:13:43.417 25942 25942 D NLService:
05-13 22:13:43.417 25942 25942 D NLService: **********************
05-13 22:13:53.425 25942 25942 D NLService: 接受到通知消息
05-13 22:13:53.425 25942 25942 D NLService: -----------------
05-13 22:13:53.425 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:13:53.425 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:13:53.426 25942 25942 D NLService: 2019-05-13 22:13
05-13 22:13:53.426 25942 25942 D NLService:
05-13 22:13:53.426 25942 25942 D NLService:
05-13 22:13:53.426 25942 25942 D NLService: **********************
05-13 22:14:06.677 25942 25976 D NLService: once socketio timer task run
05-13 22:14:06.678 25942 25976 D NLService: socketio timer task not have a server
05-13 22:14:07.591 25942 25942 D NLService: 接受到通知消息
05-13 22:14:07.591 25942 25942 D NLService: -----------------
05-13 22:14:07.591 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:14:07.591 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:14:07.594 25942 25942 D NLService: 2019-05-13 22:14
05-13 22:14:07.594 25942 25942 D NLService:
05-13 22:14:07.594 25942 25942 D NLService:
05-13 22:14:07.594 25942 25942 D NLService: **********************
05-13 22:14:12.042 25942 25942 D NLService: 接受到通知消息
05-13 22:14:12.043 25942 25942 D NLService: -----------------
05-13 22:14:12.043 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:14:12.043 25942 25942 D NLService: 包名是com.android.mms
05-13 22:14:12.044 25942 25942 D NLService: 2019-05-13 22:14
05-13 22:14:12.044 25942 25942 D NLService: “短信”正在运行
05-13 22:14:12.044 25942 25942 D NLService: 点按即可了解详情或停止应用。
05-13 22:14:12.044 25942 25942 D NLService: **********************
05-13 22:14:12.046 25942 25942 D NLService: 接受到通知消息
05-13 22:14:12.046 25942 25942 D NLService: -----------------
05-13 22:14:12.046 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:14:12.046 25942 25942 D NLService: 包名是com.android.mms
05-13 22:14:12.049 25942 25942 D NLService: 2019-05-13 22:14
05-13 22:14:12.049 25942 25942 D NLService: “短信”正在运行
05-13 22:14:12.049 25942 25942 D NLService: 点按即可了解详情或停止应用。
05-13 22:14:12.049 25942 25942 D NLService: **********************
05-13 22:14:17.642 25942 25942 D NLService: 接受到通知消息
05-13 22:14:17.642 25942 25942 D NLService: -----------------
05-13 22:14:17.642 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:14:17.642 25942 25942 D NLService: 包名是com.miui.securitycenter
05-13 22:14:17.644 25942 25942 D NLService: 2019-05-13 22:14
05-13 22:14:17.644 25942 25942 D NLService:
05-13 22:14:17.644 25942 25942 D NLService:
05-13 22:14:17.644 25942 25942 D NLService: **********************

**Comment by qi-guozheng** [comment]
2019-05-13 22:12:51.362 11519-11604/com.weihuagu.receiptnotice D/NLService: socketio timer task not have a server
2019-05-13 22:12:56.379 17596-17596/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
2019-05-13 22:12:56.381 17596-17596/? D/AndroidRuntime: CheckJNI is ON
2019-05-13 22:12:56.404 17596-17596/? W/art: Unexpected CPU variant for X86 using defaults: x86
2019-05-13 22:12:56.410 17596-17596/? D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
2019-05-13 22:12:56.428 17596-17596/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2019-05-13 22:12:56.428 17596-17596/? E/android.os.Debug: failed to load memtrack module: -2
2019-05-13 22:12:56.429 17596-17596/? I/Radio-JNI: register_android_hardware_Radio DONE
2019-05-13 22:12:56.436 17596-17596/? D/AndroidRuntime: Calling main entry com.android.commands.pm.Pm
2019-05-13 22:12:56.450 17596-17604/? W/MessageQueue: Handler (android.os.Handler) {65f278} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {65f278} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.post(Handler.java:338)
        at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
        at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
        at android.os.Binder.execTransact(Binder.java:565)
2019-05-13 22:12:56.453 17596-17596/? I/art: System.exit called, status: 0
2019-05-13 22:12:56.453 17596-17596/? I/AndroidRuntime: VM exiting with result code 0.
2019-05-13 22:14:07.012 17670-17670/? D/AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 2000 <<<<<<
2019-05-13 22:14:07.013 17670-17670/? D/AndroidRuntime: CheckJNI is ON
2019-05-13 22:14:07.035 17670-17670/? W/art: Unexpected CPU variant for X86 using defaults: x86
2019-05-13 22:14:07.040 17670-17670/? D/ICU: No timezone override file found: /data/misc/zoneinfo/current/icu/icu_tzdata.dat
2019-05-13 22:14:07.058 17670-17670/? E/memtrack: Couldn't load memtrack module (No such file or directory)
2019-05-13 22:14:07.058 17670-17670/? E/android.os.Debug: failed to load memtrack module: -2
2019-05-13 22:14:07.059 17670-17670/? I/Radio-JNI: register_android_hardware_Radio DONE
2019-05-13 22:14:07.067 17670-17670/? D/AndroidRuntime: Calling main entry com.android.commands.pm.Pm
2019-05-13 22:14:07.080 17670-17670/? I/art: System.exit called, status: 0
2019-05-13 22:14:07.080 17670-17678/? W/MessageQueue: Handler (android.os.Handler) {c2ff8db} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.os.Handler) {c2ff8db} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:543)
        at android.os.Handler.enqueueMessage(Handler.java:643)
        at android.os.Handler.sendMessageAtTime(Handler.java:612)
        at android.os.Handler.sendMessageDelayed(Handler.java:582)
        at android.os.Handler.post(Handler.java:338)
        at android.os.ResultReceiver$MyResultReceiver.send(ResultReceiver.java:57)
        at com.android.internal.os.IResultReceiver$Stub.onTransact(IResultReceiver.java:58)
        at android.os.Binder.execTransact(Binder.java:565)
2019-05-13 22:14:07.080 17670-17670/? I/AndroidRuntime: VM exiting with result code 0.

**Comment by WeihuaGu** [comment]
收到款后设置里的推送记录也是空白吗？

**Comment by qi-guozheng** [comment]
是的，推送记录里无数据

**Comment by WeihuaGu** [comment]
你是用的转账还是个人的收款码，从通知看，这个通知获取不到金额，只能看到成功转了一笔钱.
```
05-13 22:12:40.407 25942 25942 D NLService: 接受到通知消息
05-13 22:12:40.407 25942 25942 D NLService: -----------------
05-13 22:12:40.409 25942 25942 D NLService: 这是检测之外的其它通知
05-13 22:12:40.409 25942 25942 D NLService: 包名是com.eg.android.AlipayGphone
05-13 22:12:40.409 25942 25942 D NLService: 2019-05-13 22:12
05-13 22:12:40.409 25942 25942 D NLService: 支付宝消息
05-13 22:12:40.409 25942 25942 D NLService: **已成功向你转了1笔钱
05-13 22:12:40.409 25942 25942 D NLService: **********************
```

**Comment by qi-guozheng** [comment]
刚才测试了下，是在转账的情况下获取不到金额，扫码支付是获取到金额，另外想请问下，扫码支付时定义的其他信息（收款理由、备注等）可以获取的到么

**Comment by WeihuaGu** [comment]
使用这种方法不行，可以参考[wiki](https://github.com/WeihuaGu/receiptnotice/wiki)。
